-- USE sys;

DROP DATABASE IF EXISTS @DBNAME;

CREATE SCHEMA @DBNAME DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;

USE @DBNAME;

CREATE TABLE USER_TEST (
    ID_USER INT AUTO_INCREMENT NOT NULL,
    COD_USER INT NOT NULL,
    USER_NAME VARCHAR (64) NOT NULL,
    COD_USER_REF BIGINT NULL,
    PASSWORD_MD5 CHAR(32) NOT NULL,
    INPUT_DATE DATETIME NOT NULL,
    USER_STATUS CHAR(1) NOT NULL,
    PRIMARY KEY(ID_USER)
);

INSERT INTO USER_TEST (COD_USER, USER_NAME, COD_USER_REF, PASSWORD_MD5, INPUT_DATE, USER_STATUS)
    VALUES(44, 'First User Used For Tests', 1234567890123456, MD5('password123'), '2020-03-29 18:03:12', 'A')
